excluded:
  - .build

included:
  - Sources
  - Tests

# If true, SwiftLint will treat all warnings as errors.
strict: true

only_rules:
 - trailing_comma
 - vertical_whitespace
 - literal_expression_end_indentation

trailing_comma:
  mandatory_comma: true
